import {
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  OnDestroy,
  Output,
  ViewChild,
  computed,
  effect,
  inject,
  input,
  signal,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize, forkJoin, merge } from 'rxjs';
import {
  AdminCategory,
  AdminProduct,
  AdminProductInput,
} from '../../../../core/interfaces/admin.interface';
import { AdminSubcategoryStoreService } from '../../../../core/services/admin-subcategory-store.service';
import { AdminService } from '../../../../core/services/admin.service';
import { ToastService } from '../../../../core/services/toast.service';

const PRODUCT_MANAGER_ORDER_STORAGE_KEY = 'bsr.admin.product-manager.order.v1';

@Component({
  selector: 'app-admin-product-manager',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './product-manager.html',
})
export class AdminProductManager implements OnDestroy {
  private readonly adminService = inject(AdminService);
  private readonly subcategoryStore = inject(AdminSubcategoryStoreService);
  private readonly formBuilder = inject(FormBuilder);
  private readonly toastService = inject(ToastService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly currencyFormatter = new Intl.NumberFormat('es-ES', {
    style: 'currency',
    currency: 'EUR',
    maximumFractionDigits: 2,
  });
  @ViewChild('editorPanel') private editorPanel?: ElementRef<HTMLElement>;
  private objectUrl: string | null = null;
  private lastFilterKey: string | null = null;

  readonly showHeader = input(true);
  readonly headerTitle = input('Catálogo visual');
  readonly headerDescription = input(
    'Crea productos, sube imágenes y ajusta stock para que la tienda muestre cards reales.',
  );
  readonly fixedCategoryId = input<number | null>(null);
  readonly fixedSubcategory = input<string | null>(null);

  @Output() readonly changed = new EventEmitter<void>();

  readonly products = signal<readonly AdminProduct[]>([]);
  readonly categories = signal<readonly AdminCategory[]>([]);
  readonly loading = signal(true);
  readonly saving = signal(false);
  readonly selectedProductId = signal<number | null>(null);
  readonly draggedProductId = signal<number | null>(null);
  readonly dropTargetProductId = signal<number | null>(null);
  readonly imageFile = signal<File | null>(null);
  readonly imagePreview = signal<string | null>(null);
  readonly brokenImageIds = signal<readonly number[]>([]);
  readonly autoGeneratedEditSku = signal(false);
  readonly productOrders = signal<Record<string, readonly number[]>>(this.readStoredProductOrders());
  readonly isEditing = computed(() => this.selectedProductId() !== null);
  readonly showCategoryField = computed(() => this.fixedCategoryId() === null);
  readonly currentOrderKey = computed(
    () => `${this.fixedCategoryId() ?? 'all'}:${this.fixedSubcategory() ?? 'all'}`,
  );
  readonly currentCategory = computed(
    () => this.categories().find((category) => category.id === this.fixedCategoryId()) ?? null,
  );
  readonly currentSubcategory = computed(() => {
    const fixedCategoryId = this.fixedCategoryId();
    const fixedSubcategory = this.fixedSubcategory();

    if (fixedCategoryId === null || fixedSubcategory === null) {
      return null;
    }

    return this.subcategoryStore.getSubcategory(
      fixedCategoryId,
      fixedSubcategory,
      this.categories(),
      this.products(),
    );
  });
  readonly filteredProducts = computed<readonly AdminProduct[]>(() => {
    let filteredProducts = this.products();
    const fixedCategoryId = this.fixedCategoryId();
    const fixedSubcategory = this.fixedSubcategory();

    if (fixedCategoryId !== null) {
      filteredProducts = filteredProducts.filter((product) => product.categoryId === fixedCategoryId);
    }

    if (fixedSubcategory !== null) {
      filteredProducts = filteredProducts.filter(
        (product) =>
          this.subcategoryStore.getAssignedSubcategorySlug(
            product.id,
            product.categoryId,
            this.categories(),
            this.products(),
          ) === fixedSubcategory,
      );
    }

    const storedOrder = this.productOrders()[this.currentOrderKey()] ?? [];

    if (!storedOrder.length) {
      return filteredProducts;
    }

    const productsById = new Map(filteredProducts.map((product) => [product.id, product]));
    const orderedProducts = storedOrder.flatMap((productId) => {
      const product = productsById.get(productId);
      return product ? [product] : [];
    });

    return [
      ...orderedProducts,
      ...filteredProducts.filter((product) => !storedOrder.includes(product.id)),
    ];
  });

  readonly form = this.formBuilder.group({
    name: ['', [Validators.required, Validators.maxLength(150)]],
    sku: ['', [Validators.maxLength(80)]],
    description: ['', [Validators.required, Validators.maxLength(2000)]],
    price: [null as number | null, [Validators.required, Validators.min(0.01)]],
    stock: [50, [Validators.required, Validators.min(0)]],
    categoryId: [null as number | null, [Validators.required]],
    imageUrl: [''],
  });

  constructor() {
    merge(this.form.controls.categoryId.valueChanges, this.form.controls.name.valueChanges)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(() => this.syncGeneratedSku());

    effect(() => {
      const fixedCategoryId = this.fixedCategoryId();
      const fixedSubcategory = this.fixedSubcategory();
      const filterKey = `${fixedCategoryId ?? 'all'}:${fixedSubcategory ?? 'none'}`;

      if (this.lastFilterKey !== null && this.lastFilterKey !== filterKey) {
        this.startCreate();
      } else if (
        fixedCategoryId !== null &&
        this.form.controls.categoryId.value !== fixedCategoryId
      ) {
        this.form.patchValue({ categoryId: fixedCategoryId }, { emitEvent: false });
        this.syncGeneratedSku();
      }

      this.lastFilterKey = filterKey;
    });

    this.loadData();
  }

  ngOnDestroy(): void {
    this.releaseObjectUrl();
  }

  loadData(resetForm = false): void {
    this.loading.set(true);

    forkJoin({
      products: this.adminService.getProducts(),
      categories: this.adminService.getCategories(),
    })
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: ({ products, categories }) => {
          this.brokenImageIds.set([]);
          const categoriesById = new Map(categories.map((category) => [category.id, category.name]));

          this.products.set(
            products.map((product) => ({
              ...product,
              categoryName:
                (product.categoryId !== null ? categoriesById.get(product.categoryId) : null) ||
                product.categoryName,
            })),
          );
          this.categories.set(categories);

          if (resetForm) {
            this.startCreate();
            return;
          }

          const defaultCategoryId = this.fixedCategoryId() ?? categories[0]?.id ?? null;

          if (defaultCategoryId !== null && this.form.controls.categoryId.value !== defaultCategoryId) {
            this.form.patchValue({ categoryId: defaultCategoryId }, { emitEvent: false });
          }

          this.syncGeneratedSku();
        },
        error: () => {
          this.products.set([]);
          this.categories.set([]);
          this.toastService.showError(
            'No se pudieron cargar los productos o las categorías del panel admin.',
          );
        },
      });
  }

  startCreate(): void {
    this.selectedProductId.set(null);
    this.autoGeneratedEditSku.set(false);
    this.imageFile.set(null);
    this.setPreview(null);

    const defaultCategoryId = this.fixedCategoryId() ?? this.categories()[0]?.id ?? null;

    this.form.reset({
      name: '',
      sku: this.generateSkuPreview(defaultCategoryId),
      description: '',
      price: null,
      stock: 50,
      categoryId: defaultCategoryId,
      imageUrl: '',
    });
  }

  startEdit(product: AdminProduct): void {
    this.selectedProductId.set(product.id);
    const normalizedSku = this.normalizeSku(product.sku);

    this.autoGeneratedEditSku.set(!normalizedSku);
    this.imageFile.set(null);
    this.form.reset({
      name: product.name,
      sku: normalizedSku,
      description: product.description,
      price: product.price,
      stock: product.stock ?? 0,
      categoryId: product.categoryId,
      imageUrl: product.imageUrl ?? '',
    });
    this.syncGeneratedSku();
    this.setPreview(product.imageUrl);
    this.scrollEditorIntoView();
  }

  isBrokenImage(productId: number): boolean {
    return this.brokenImageIds().includes(productId);
  }

  markImageAsBroken(productId: number): void {
    if (this.brokenImageIds().includes(productId)) {
      return;
    }

    this.brokenImageIds.update((ids) => [...ids, productId]);
  }

  imageSrc(product: AdminProduct): string | null {
    if (!product.imageUrl) {
      return null;
    }

    const version = product.updatedAt ?? product.createdAt;

    if (!version) {
      return product.imageUrl;
    }

    const separator = product.imageUrl.includes('?') ? '&' : '?';
    return `${product.imageUrl}${separator}v=${encodeURIComponent(version)}`;
  }

  displayName(product: AdminProduct): string {
    return product.name?.trim() || `Producto #${product.id}`;
  }

  displayCategory(product: AdminProduct): string {
    return product.categoryName?.trim() || 'Sin categoría';
  }

  displayPrice(price: number | null): string {
    return price === null ? 'Consultar' : this.currencyFormatter.format(price);
  }

  displayStock(stock: number | null): string {
    return String(stock ?? 0);
  }

  displayImageStatus(product: AdminProduct): string {
    return product.imageUrl && !this.isBrokenImage(product.id) ? 'Imagen conectada' : 'Sin imagen';
  }

  startCardDrag(event: DragEvent, productId: number): void {
    this.draggedProductId.set(productId);
    this.dropTargetProductId.set(productId);
    event.dataTransfer?.setData('text/plain', String(productId));

    if (event.dataTransfer) {
      event.dataTransfer.effectAllowed = 'move';
    }
  }

  onCardDragOver(event: DragEvent, productId: number): void {
    if (this.draggedProductId() === null) {
      return;
    }

    event.preventDefault();

    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move';
    }

    if (this.draggedProductId() !== productId) {
      this.dropTargetProductId.set(productId);
    }
  }

  onCardDrop(event: DragEvent, targetProductId: number): void {
    event.preventDefault();

    const sourceProductId = this.draggedProductId();

    if (sourceProductId === null || sourceProductId === targetProductId) {
      this.resetCardDragState();
      return;
    }

    const currentOrder = this.filteredProducts().map((product) => product.id);
    const sourceIndex = currentOrder.indexOf(sourceProductId);
    const targetIndex = currentOrder.indexOf(targetProductId);

    if (sourceIndex === -1 || targetIndex === -1) {
      this.resetCardDragState();
      return;
    }

    const nextOrder = [...currentOrder];
    const [movedProductId] = nextOrder.splice(sourceIndex, 1);
    nextOrder.splice(targetIndex, 0, movedProductId);

    const orderKey = this.currentOrderKey();
    this.productOrders.update((orders) => ({
      ...orders,
      [orderKey]: nextOrder,
    }));
    this.writeStoredProductOrders(this.productOrders());
    this.resetCardDragState();
  }

  endCardDrag(): void {
    this.resetCardDragState();
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.toastService.showFormValidationError();
      return;
    }

    const rawValue = this.form.getRawValue();
    const categoryId = Number(rawValue.categoryId);
    const price =
      typeof rawValue.price === 'number' && Number.isFinite(rawValue.price)
        ? rawValue.price
        : Number.NaN;
    const selectedProductId = this.selectedProductId();
    const normalizedName = this.normalizeProductName(rawValue.name);

    if (!Number.isFinite(categoryId) || categoryId <= 0) {
      this.form.controls.categoryId.markAsTouched();
      this.toastService.showFormValidationError();
      return;
    }

    if (!Number.isFinite(price) || price <= 0) {
      this.form.controls.price.markAsTouched();
      this.toastService.showFormValidationError();
      return;
    }

    if (this.hasDuplicateProductName(normalizedName, selectedProductId)) {
      this.toastService.showError('Ya existe un producto con ese nombre. Cámbialo antes de guardar.');
      return;
    }

    const requestedSku = this.normalizeSku(rawValue.sku);
    const resolvedSku =
      selectedProductId === null
        ? this.generateUniqueSku(categoryId)
        : requestedSku || this.generateUniqueSku(categoryId, selectedProductId);

    this.form.patchValue({ sku: resolvedSku }, { emitEvent: false });

    const payload: AdminProductInput = {
      name: rawValue.name?.trim() || '',
      sku: resolvedSku,
      description: rawValue.description?.trim() || '',
      price,
      stock: Number(rawValue.stock ?? 0),
      categoryId,
      imageUrl: rawValue.imageUrl?.trim() || null,
      imageFile: this.imageFile(),
    };

    const request$ =
      selectedProductId === null
        ? this.adminService.createProduct(payload)
        : this.adminService.updateProduct(selectedProductId, payload);

    this.saving.set(true);

    request$.pipe(finalize(() => this.saving.set(false))).subscribe({
      next: (product) => {
        this.syncProductSubcategory(product, categoryId);
        this.applyStoredImageUrl(product.imageUrl);
        this.toastService.show({
          title: selectedProductId === null ? 'Producto creado' : 'Producto actualizado',
          message: `El producto ${product.name} ya está sincronizado con el panel admin.`,
        });
        this.loadData(true);
        this.changed.emit();
      },
      error: (error) => {
        this.toastService.showError(this.translateProductSaveError(error.error?.message));
      },
    });
  }

  deleteProduct(product: AdminProduct): void {
    const confirmed = window.confirm(`¿Quieres eliminar el producto "${product.name}"?`);

    if (!confirmed) {
      return;
    }

    this.subcategoryStore.removeProductAssignment(product.id);
    this.saving.set(true);

    this.adminService
      .deleteProduct(product.id)
      .pipe(finalize(() => this.saving.set(false)))
      .subscribe({
        next: () => {
          this.toastService.show({
            title: 'Producto eliminado',
            message: `El producto ${product.name} se ha eliminado correctamente.`,
          });
          this.loadData();

          if (this.selectedProductId() === product.id) {
            this.startCreate();
          }

          this.changed.emit();
        },
        error: () => {
          this.toastService.showError('No se pudo eliminar el producto.');
        },
      });
  }

  onImageFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0] ?? null;

    this.imageFile.set(file);

    if (!file) {
      this.setPreview(this.form.controls.imageUrl.value?.trim() || null);
      return;
    }

    const previewUrl = URL.createObjectURL(file);
    this.form.patchValue({ imageUrl: previewUrl });
    this.setPreview(previewUrl, true);
  }

  onImageUrlInput(): void {
    if (this.imageFile()) {
      return;
    }

    this.setPreview(this.form.controls.imageUrl.value?.trim() || null);
  }

  clearImage(): void {
    this.imageFile.set(null);
    this.form.patchValue({ imageUrl: '' });
    this.setPreview(null);
  }

  private setPreview(url: string | null, isObjectUrl = false): void {
    this.releaseObjectUrl();

    if (isObjectUrl && url) {
      this.objectUrl = url;
    }

    this.imagePreview.set(url);
  }

  private releaseObjectUrl(): void {
    if (this.objectUrl) {
      URL.revokeObjectURL(this.objectUrl);
      this.objectUrl = null;
    }
  }

  private applyStoredImageUrl(imageUrl: string | null): void {
    const normalizedImageUrl = imageUrl?.trim() || '';

    if (!normalizedImageUrl) {
      return;
    }

    this.form.patchValue({ imageUrl: normalizedImageUrl });

    if (!window.isSecureContext || !navigator.clipboard?.writeText) {
      return;
    }

    void navigator.clipboard.writeText(normalizedImageUrl).catch(() => undefined);
  }

  private syncGeneratedSku(): void {
    const selectedProductId = this.selectedProductId();

    if (selectedProductId !== null) {
      if (!this.autoGeneratedEditSku()) {
        return;
      }

      this.form.patchValue(
        {
          sku: this.generateUniqueSku(this.form.controls.categoryId.value, selectedProductId),
        },
        { emitEvent: false },
      );
      return;
    }

    this.form.patchValue(
      {
        sku: this.generateSkuPreview(this.form.controls.categoryId.value),
      },
      { emitEvent: false },
    );
  }

  private generateSkuPreview(categoryId: number | null): string {
    return this.generateUniqueSku(categoryId);
  }

  private generateUniqueSku(
    categoryId: number | null,
    excludedProductId: number | null = null,
  ): string {
    const categoryName =
      this.categories().find((category) => category.id === categoryId)?.name ?? null;
    const categoryCode = this.resolveCategoryCode(categoryName);
    const skuPrefix = `BSR-${categoryCode}-`;
    const usedSkus = new Set(
      this.products()
        .filter((product) => product.id !== excludedProductId)
        .map((product) => this.normalizeSku(product.sku))
        .filter((sku) => !!sku),
    );
    let nextSequence = 1;

    for (const sku of usedSkus) {
      if (!sku.startsWith(skuPrefix)) {
        continue;
      }

      const sequence = Number(sku.slice(skuPrefix.length));

      if (Number.isInteger(sequence) && sequence >= nextSequence) {
        nextSequence = sequence + 1;
      }
    }

    let candidateSku = `${skuPrefix}${String(nextSequence).padStart(4, '0')}`;

    while (usedSkus.has(candidateSku)) {
      nextSequence += 1;
      candidateSku = `${skuPrefix}${String(nextSequence).padStart(4, '0')}`;
    }

    return candidateSku;
  }

  private normalizeSku(value: string | null | undefined): string {
    return value?.trim().toUpperCase() || '';
  }

  private normalizeProductName(value: string | null | undefined): string {
    return value?.trim().toLowerCase() || '';
  }

  private hasDuplicateProductName(name: string, excludedProductId: number | null = null): boolean {
    if (!name) {
      return false;
    }

    return this.products().some(
      (product) =>
        product.id !== excludedProductId && this.normalizeProductName(product.name) === name,
    );
  }

  private translateProductSaveError(message: string | null | undefined): string {
    const normalizedMessage = message?.trim();

    if (!normalizedMessage) {
      return 'No se pudo guardar el producto. Revisa los datos del formulario.';
    }

    if (normalizedMessage === 'Price is required') {
      return 'El precio es obligatorio.';
    }

    if (
      normalizedMessage === 'Price is invalid' ||
      normalizedMessage === 'Price must be greater than 0'
    ) {
      return 'El precio debe ser mayor que 0.';
    }

    switch (normalizedMessage) {
      case 'A product with that name already exists':
        return 'Ya existe un producto con ese nombre.';
      case 'A product with that sku already exists':
        return 'Ya existe un producto con ese SKU.';
      case 'Category not found':
        return 'La categoría seleccionada no existe.';
      case 'Only image files are allowed':
        return 'El archivo seleccionado debe ser una imagen válida.';
      case 'Unexpected error occurred':
        return 'Ha ocurrido un error inesperado al guardar el producto.';
      default:
        return normalizedMessage;
    }
  }

  private syncProductSubcategory(product: AdminProduct, categoryId: number): void {
    const fixedSubcategory = this.fixedSubcategory();

    if (!fixedSubcategory) {
      return;
    }

    this.subcategoryStore.saveProductAssignment(
      product.id,
      categoryId,
      fixedSubcategory,
      this.categories(),
      [...this.products(), product],
    );
  }

  private scrollEditorIntoView(): void {
    window.setTimeout(() => {
      this.editorPanel?.nativeElement.scrollIntoView({
        behavior: 'smooth',
        block: 'start',
      });
    }, 40);
  }

  private resolveCategoryCode(categoryName: string | null): string {
    const normalizedCategory = (categoryName ?? '')
      .trim()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .toUpperCase();

    if (!normalizedCategory) {
      return 'GEN';
    }

    if (normalizedCategory.startsWith('WOM')) {
      return 'WOM';
    }
    if (normalizedCategory.startsWith('MEN') || normalizedCategory.startsWith('HOM')) {
      return 'MEN';
    }
    if (
      normalizedCategory.startsWith('KID') ||
      normalizedCategory.startsWith('NIN') ||
      normalizedCategory.startsWith('CHI')
    ) {
      return 'KID';
    }
    if (normalizedCategory.startsWith('ACC') || normalizedCategory.startsWith('COM')) {
      return 'ACC';
    }

    return (normalizedCategory.replace(/\s+/g, '') + 'XXX').slice(0, 3);
  }

  private resetCardDragState(): void {
    this.draggedProductId.set(null);
    this.dropTargetProductId.set(null);
  }

  private readStoredProductOrders(): Record<string, readonly number[]> {
    if (typeof localStorage === 'undefined') {
      return {};
    }

    try {
      const rawValue = localStorage.getItem(PRODUCT_MANAGER_ORDER_STORAGE_KEY);
      const parsedValue = rawValue ? (JSON.parse(rawValue) as unknown) : {};

      if (!parsedValue || typeof parsedValue !== 'object') {
        return {};
      }

      return Object.fromEntries(
        Object.entries(parsedValue as Record<string, unknown>).flatMap(([key, value]) => {
          if (!Array.isArray(value)) {
            return [];
          }

          const normalizedOrder = value.flatMap((entry) => {
            const productId = Number(entry);
            return Number.isInteger(productId) && productId > 0 ? [productId] : [];
          });

          return normalizedOrder.length ? [[key, normalizedOrder]] : [];
        }),
      );
    } catch {
      return {};
    }
  }

  private writeStoredProductOrders(orders: Record<string, readonly number[]>): void {
    if (typeof localStorage === 'undefined') {
      return;
    }

    try {
      localStorage.setItem(PRODUCT_MANAGER_ORDER_STORAGE_KEY, JSON.stringify(orders));
    } catch {}
  }
}
